### ISSUE TITLE
Attribute "multi" of DCov class undefined if False

### ISSUE THREAD

**Issue by flblanc** [bio-phys/DiffusionGLS#2]
Hi,
When trying to use `Dfit` on a single position time-series (as a test run), I obtain the following error:

`AttributeError: Dcov instance has no attribute 'multi'` 

Looking in the code, line 304:

``` python
self.fz = fz
        if type(self.fz) in (list, tuple):
            self.multi = True
            print('Analyzing trajectories of multiple molecules from the same simulation.')
        else:
            print('Analyzing single trajectory.')
```
There is no `self.multi = False` in the `else` block, which I assume leads to the above error. If I add the `self.multi = False` declaration the error disappears. Could you please fix that? 

Thanks in advance ! 
Florian

**Comment by sobuelow** [comment]
Thanks, fixed!
